spring:
  datasource:
    url: jdbc:mysql://localhost/tasktracker
    username: root
    password:           
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
security:
  basic:
    enabled: false
  user:
    password: admin            
token:
  secret: 9SyECk96oDsTmXfogIieDI0cD/8FpnojlYSUJT5U9I/FGVmBz5oskmjOR8cbXTvoPjX+Pq/T/b1PqpHX0lYm0oCBjXWICA==
logging:
  level:
    org.springframework.security: DEBUG